name: 🌍 Add New Language
description: Help translate Ticket Time Legacy into a new language! Translate the information i.e. "🎫 Create a Ticket", into a language you can speak.
labels: ["translation", "help wanted"]
body:
  - type: input
    id: language_name
    attributes:
      label: Language Name
      placeholder: e.g. Spanish
  - type: input
    id: language_code
    attributes:
      label: Language Code
      placeholder: e.g. es
  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: |
        Copy the JSON below, translate the values, and paste it back here with your changes.
        Do **not** change the keys.
      placeholder: |
{
    "name": "English",
    "code": "en",
    "translations": {
        "create_button": "🎫 Create a Ticket",
        "channel_name": "ticket-for-{}",
        "error_already_have_ticket": "You already have a ticket open at {}!",
        "error_no_mod_role": "There is no support role setup for this server. Please ask staff to set it up. If you are staff, and the support role is setup, please contact support.",
        "error_no_category": "There is no ticket category setup for this server. Please ask staff to set it up. If you are staff, and the ticket category is setup, please contact support.",
        "error_no_blacklisted_role": "There is no blacklisted role setup for this server. Please ask staff to set it up. If you are staff, and the blacklisted role is setup, please contact support.",
        "error_user_blacklisted": "You have been blacklisted by staff. Speak to a server admin if you believe this is a mistake.",
        "created_reason": "Ticket for {}",
        "log_created_title": "Ticket Created",
        "log_creator_field": "Ticket Creator",
        "log_mod_role": "Ticket Moderation Team Role",
        "log_created_in": "Created in",
        "log_created_timestamp": "Time Created",
        "log_created_description": "A ticket has been opened by a member of this server.\n*Only a Ticket Moderator can delete the ticket. Everyone but staff and owner will receive a transcript to direct messages and staff can get one after ticket closes.*",
        "create_response": "{} I've created a ticket for you in {}!",
        "close_confirm_button": "Confirm",
        "close_dm_title": "{}",
        "close_dm_description": "A ticket you were in has been closed.",
        "close_dm_ticket_name": "Ticket Name",
        "close_dm_server": "Ticket Server",
        "close_dm_support_server": "Support Server",
        "close_dm_transcript": "Ticket Transcript",
        "close_dm_transcript_value": "View ticket transcript above. Download and Open to see full transcript like a discord channel.",
        "close_response_title": "Ticket Closed",
        "close_response_description": "This ticket has been closed and everyone without the support role has been removed!",
        "log_closed_title": "Ticket Closed",
        "log_closed_description": "A ticket has just been closed.",
        "log_closed_ticket_name": "Ticket Name",
        "log_closed_by": "Closed by",
        "log_closed_timestamp": "Time Closed",
        "delete_button": "✖️ Delete Ticket",
        "error_delete_not_allowed": "You are not allowed to delete this ticket.",
        "error_generic": "Something went wrong, please try again later or contact support if the issue persists.",
        "transcript_button": "📑 Transcript",
        "transcript_response": "A transcript of this ticket has been attached below.",
        "transcript_tip": "You can run `/ticketlogs` to get automatic transcripts sent to the logs when tickets get closed.",
        "error_transcript_not_allowed": "You are not allowed to get a transcript for this ticket.",
        "close_button": "✖️ Close Ticket",
        "close_confirmation": "Are you sure you want to close this ticket?",
        "ping_button": "📢 Ping Support",
        "error_ping_cooldown": "You are on cooldown! Please wait before pinging staff again! You can ping staff again <t:{}:R>",
        "ping_response": "{} You have been pinged due to a request by {}",
        "rate_button": "🌟 Rate Us"
    }
} |
